//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontendMentor.ResultsSummaryComponent.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrontendMentor.ResultsSummaryComponent.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string ResultsSummaryComponentView_ContinueTextBlock_Text {
            get {
                return ResourceManager.GetString("ResultsSummaryComponentView_ContinueTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of 100.
        /// </summary>
        public static string ResultsSummaryComponentView_NumberScoreOf100TextBlock_Text {
            get {
                return ResourceManager.GetString("ResultsSummaryComponentView_NumberScoreOf100TextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your performance exceed {0}% of the people conducting the test here!.
        /// </summary>
        public static string ResultsSummaryComponentView_PerformanceTextBlock_StringFormat {
            get {
                return ResourceManager.GetString("ResultsSummaryComponentView_PerformanceTextBlock_StringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Result.
        /// </summary>
        public static string ResultsSummaryComponentView_ResultTextBlock_Text {
            get {
                return ResourceManager.GetString("ResultsSummaryComponentView_ResultTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string ResultsSummaryComponentView_SummaryTextBlock_Text {
            get {
                return ResourceManager.GetString("ResultsSummaryComponentView_SummaryTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Summary Component.
        /// </summary>
        public static string ResultSummaryComponentWindow_Title {
            get {
                return ResourceManager.GetString("ResultSummaryComponentWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory.
        /// </summary>
        public static string SummaryItemType_Memory {
            get {
                return ResourceManager.GetString("SummaryItemType_Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaction.
        /// </summary>
        public static string SummaryItemType_Reaction {
            get {
                return ResourceManager.GetString("SummaryItemType_Reaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbal.
        /// </summary>
        public static string SummaryItemType_Verbal {
            get {
                return ResourceManager.GetString("SummaryItemType_Verbal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual.
        /// </summary>
        public static string SummaryItemType_Visual {
            get {
                return ResourceManager.GetString("SummaryItemType_Visual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string TextBlock_Fallback_Text {
            get {
                return ResourceManager.GetString("TextBlock_Fallback_Text", resourceCulture);
            }
        }
    }
}
