//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontendMentor.ThreeColumnPreviewCardComponent.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrontendMentor.ThreeColumnPreviewCardComponent.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cruise in the best car brands without the bloated prices. Enjoy the enhanced comfort of a luxury rental and arrive in style..
        /// </summary>
        public static string Luxury_PreviewCard_Caption {
            get {
                return ResourceManager.GetString("Luxury_PreviewCard_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUXURY.
        /// </summary>
        public static string Luxury_PreviewCard_Title {
            get {
                return ResourceManager.GetString("Luxury_PreviewCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string PreviewCard_LearnMoreButton_Content {
            get {
                return ResourceManager.GetString("PreviewCard_LearnMoreButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a sedan for its affordability and excellent fuel economy. Ideal for cruising in the city or on your next road trip..
        /// </summary>
        public static string Sedan_PreviewCard_Caption {
            get {
                return ResourceManager.GetString("Sedan_PreviewCard_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEDANS.
        /// </summary>
        public static string Sedan_PreviewCard_Title {
            get {
                return ResourceManager.GetString("Sedan_PreviewCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take an SUV for its spacious interior, power, and versatility. Perfect for your next family vacation and off-road adventures..
        /// </summary>
        public static string Suv_PreviewCard_Caption {
            get {
                return ResourceManager.GetString("Suv_PreviewCard_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUVS.
        /// </summary>
        public static string Suv_PreviewCard_Title {
            get {
                return ResourceManager.GetString("Suv_PreviewCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three column preview card component.
        /// </summary>
        public static string ThreeColumnPreviewCardComponentWindow_Title {
            get {
                return ResourceManager.GetString("ThreeColumnPreviewCardComponentWindow_Title", resourceCulture);
            }
        }
    }
}
