<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Properties\Icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Fonts\Fraunces\Fraunces-Italic-VariableFont_SOFT,WONK,opsz,wght.ttf" />
    <None Remove="Fonts\Fraunces\Fraunces-VariableFont_SOFT,WONK,opsz,wght.ttf" />
    <None Remove="Fonts\Montserrat\Montserrat-Black.ttf" />
    <None Remove="Fonts\Montserrat\Montserrat-BlackItalic.ttf" />
    <None Remove="Fonts\Montserrat\Montserrat-Bold.ttf" />
    <None Remove="Fonts\Montserrat\Montserrat-BoldItalic.ttf" />
    <None Remove="Fonts\Montserrat\Montserrat-ExtraBold.ttf" />
    <None Remove="Fonts\Montserrat\Montserrat-ExtraBoldItalic.ttf" />
    <None Remove="Fonts\Montserrat\Montserrat-ExtraLight.ttf" />
    <None Remove="Fonts\Montserrat\Montserrat-ExtraLightItalic.ttf" />
    <None Remove="Fonts\Montserrat\Montserrat-Italic.ttf" />
    <None Remove="Fonts\Montserrat\Montserrat-Light.ttf" />
    <None Remove="Fonts\Montserrat\Montserrat-LightItalic.ttf" />
    <None Remove="Fonts\Montserrat\Montserrat-Medium.ttf" />
    <None Remove="Fonts\Montserrat\Montserrat-MediumItalic.ttf" />
    <None Remove="Fonts\Montserrat\Montserrat-Regular.ttf" />
    <None Remove="Fonts\Montserrat\Montserrat-SemiBold.ttf" />
    <None Remove="Fonts\Montserrat\Montserrat-SemiBoldItalic.ttf" />
    <None Remove="Fonts\Montserrat\Montserrat-Thin.ttf" />
    <None Remove="Fonts\Montserrat\Montserrat-ThinItalic.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Properties\Icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\FrontendMentor.Assets\FrontendMentor.Assets.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\Fraunces\Fraunces-Italic-VariableFont_SOFT,WONK,opsz,wght.ttf" />
    <Resource Include="Fonts\Fraunces\Fraunces-VariableFont_SOFT,WONK,opsz,wght.ttf" />
    <Resource Include="Fonts\Montserrat\Montserrat-Black.ttf" />
    <Resource Include="Fonts\Montserrat\Montserrat-BlackItalic.ttf" />
    <Resource Include="Fonts\Montserrat\Montserrat-Bold.ttf" />
    <Resource Include="Fonts\Montserrat\Montserrat-BoldItalic.ttf" />
    <Resource Include="Fonts\Montserrat\Montserrat-ExtraBold.ttf" />
    <Resource Include="Fonts\Montserrat\Montserrat-ExtraBoldItalic.ttf" />
    <Resource Include="Fonts\Montserrat\Montserrat-ExtraLight.ttf" />
    <Resource Include="Fonts\Montserrat\Montserrat-ExtraLightItalic.ttf" />
    <Resource Include="Fonts\Montserrat\Montserrat-Italic.ttf" />
    <Resource Include="Fonts\Montserrat\Montserrat-Light.ttf" />
    <Resource Include="Fonts\Montserrat\Montserrat-LightItalic.ttf" />
    <Resource Include="Fonts\Montserrat\Montserrat-Medium.ttf" />
    <Resource Include="Fonts\Montserrat\Montserrat-MediumItalic.ttf" />
    <Resource Include="Fonts\Montserrat\Montserrat-Regular.ttf" />
    <Resource Include="Fonts\Montserrat\Montserrat-SemiBold.ttf" />
    <Resource Include="Fonts\Montserrat\Montserrat-SemiBoldItalic.ttf" />
    <Resource Include="Fonts\Montserrat\Montserrat-Thin.ttf" />
    <Resource Include="Fonts\Montserrat\Montserrat-ThinItalic.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
