name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  pipeline:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: source
    steps:
      - uses: actions/checkout@v3
      - name: Get .NET version from global.json
        id: dotnet-version
        run: |
          DOTNET_VERSION=$(jq -r '.sdk.version' ../global.json)
          echo "DOTNET_VERSION=$DOTNET_VERSION" >> $GITHUB_ENV
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ needs.setup.outputs.dotnet-version }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Install .NET Format tool
        run: dotnet tool install -g dotnet-format
      - name: Check Code Style
        run: dotnet format --verify-no-changes --verbosity diagnostic